name: moviq
description: "A new Flutter project."
publish_to: 'none' # Prevent publishing to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.10.3

dependencies:
  flutter:
    sdk: flutter
    

  # iOS style icons
  cupertino_icons: ^1.0.8

  # Firebase core
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.0
  cloud_firestore: ^5.4.0

  # Google Sign-In
  google_sign_in: ^6.2.1

  # Apple Sign-In
  sign_in_with_apple: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
